"""
STORAGE CLEANUP UTILITY
=======================
Deletes old/redundant files from Datasets/processed to free up space.
Only keeps files generated by the FINAL pipeline.

SAFETY:
- DRY_RUN = True  -> Only prints what would be deleted.
- DRY_RUN = False -> ACTUALLY DELETES FILES.
"""

import os
from pathlib import Path
from tqdm import tqdm

# --- CONFIGURATION ---
BASE_PATH = Path(r"C:\Users\524yu\OneDrive\Documents\VSCODEE\BMI-Robotic-Control\Datasets\processed")

# 1. SET THIS TO FALSE TO ACTUALLY DELETE FILES
DRY_RUN = False  

# 2. DEFINITELY KEEP THESE (The output of your current pipeline)
PATTERNS_TO_KEEP = [
    "_cleaned_eeg.fif",      # New cleaning output
    "_spectrograms.pkl",     # New feature extraction output
    "_eegnet_features.pkl"   # New EEGNet extraction output
]

# 3. EXTENSIONS TO CHECK (Don't delete folders or random text files)
TARGET_EXTENSIONS = {".fif", ".pkl"}

def get_readable_size(size_in_bytes):
    for unit in ['B', 'KB', 'MB', 'GB']:
        if size_in_bytes < 1024.0:
            return f"{size_in_bytes:.2f} {unit}"
        size_in_bytes /= 1024.0
    return f"{size_in_bytes:.2f} TB"

def run_cleanup():
    print(f"--- STARTING CLEANUP (Dry Run: {DRY_RUN}) ---")
    print(f"Target Directory: {BASE_PATH}")
    print(f"Keeping files ending in: {PATTERNS_TO_KEEP}")
    print("-" * 60)

    total_deleted_size = 0
    files_deleted_count = 0
    
    # Walk through S001 to S109
    subject_dirs = sorted([d for d in BASE_PATH.iterdir() if d.is_dir() and d.name.startswith('S')])

    for sub_dir in tqdm(subject_dirs, desc="Scanning Subjects"):
        for file_path in sub_dir.iterdir():
            
            # Skip if it's a folder
            if not file_path.is_file():
                continue
                
            # Only look at big data files (.fif, .pkl)
            if file_path.suffix not in TARGET_EXTENSIONS:
                continue

            # CHECK: Is this file in our "Keep List"?
            is_valid = False
            for pattern in PATTERNS_TO_KEEP:
                if file_path.name.endswith(pattern):
                    is_valid = True
                    break
            
            # If it is NOT valid, delete it
            if not is_valid:
                size = file_path.stat().st_size
                total_deleted_size += size
                files_deleted_count += 1
                
                if DRY_RUN:
                    tqdm.write(f"[WOULD DELETE] {file_path.name} ({get_readable_size(size)})")
                else:
                    try:
                        os.remove(file_path)
                        # tqdm.write(f"[DELETED] {file_path.name}") # Uncomment to see every deletion
                    except Exception as e:
                        print(f"Error deleting {file_path.name}: {e}")

    print("-" * 60)
    print(f"Cleanup Complete.")
    print(f"Files {'Found' if DRY_RUN else 'Deleted'}: {files_deleted_count}")
    print(f"Space {' reclaiming' if DRY_RUN else 'Reclaimed'}: {get_readable_size(total_deleted_size)}")
    
    if DRY_RUN:
        print("\n!!! SAFETY MODE IS ON !!!")
        print("Set 'DRY_RUN = False' in the script to actually delete these files.")

if __name__ == "__main__":
    run_cleanup()